config/routes.rb
Rails.application.routes.draw do

devise_for :usuarios, :controllers => { registrations: 'usuarios/registrations' }

  namespace :api do
  namespace :v1 do
     resources :sessions, only: [:create]
     resources :retos, only: [:index]
     resources :usuarios, only: [:update]
     post 'api/v1/sessions/cerrar' => 'sessions#cerrar_sesion'
    end
  end
  resources :retos
resources :usuarios

get 'inicio' => 'estaticas#inicio'
  

  root 'estaticas#inicio'#raiz de la web app

end

app/models/logro.rb
class Logro < ActiveRecord::Base
	belongs_to :usuario
	belongs_to :reto
end

app/models/reto.rb
class Reto < ActiveRecord::Base
	#asosiaciones
	has_many :logros
	has_many :usuarios , through: :logros
	#validaciones
	validates :descripcion ,presence: true
	validates :nombre ,presence: true
	validates :latitud ,presence: true
	validates :longitud ,presence: true


end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 validates :nickname, presence: true

#asociations
has_many :logros
has_many :retos, through: :logros


 def generate_authentication_token
    
      self.authentication_token = SecureRandom.hex
     
 
    save!
 
    authentication_token
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/estaticas_controller.rb
class EstaticasController < ApplicationController
	def inicio#pagina de inicio root
		@usuarios= Usuario.all
	end
end

app/controllers/retos_controller.rb
class RetosController < ApplicationController
	def new
		@reto = Reto.new
	end

	def create
		@reto.new(retos_params)
		if @reto.valid?
			@reto.save
			redirect_to @reto
		else
			render :action => 'new'
		end
	end

	def show
		@reto = Reto.find(params[:id])
	end
	private

	def retos_params
		 params.required(:reto).permit(:nombre
     ,:descripcion
     , :latitud
      ,:longitud)
	end
end

app/controllers/usuarios/confirmations_controller.rb
class Usuarios::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/usuarios/omniauth_callbacks_controller.rb
class Usuarios::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/usuarios/passwords_controller.rb
class Usuarios::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/usuarios/registrations_controller.rb
class Usuarios::RegistrationsController < Devise::RegistrationsController
 before_action :configure_sign_up_params, only: [:create]
 before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
   def configure_sign_up_params
     devise_parameter_sanitizer.for(:sign_up) << :nickname
   end

  # You can put the params you want to permit in the empty array.
   def configure_account_update_params
    devise_parameter_sanitizer.for(:account_update) << :nickname
   end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
   
private
  def sign_up_params
    params.require(:usuario).permit(:nickname, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:usuario).permit(:nickname, :email, :password, :password_confirmation, :current_password)
  end
  
end

app/controllers/usuarios/sessions_controller.rb
class Usuarios::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/usuarios/unlocks_controller.rb
class Usuarios::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
	def show
		@usuario=Usuario.find(params[:id])
	end
end

app/helpers/api/v1/retos_helper.rb
module Api::V1::RetosHelper
end

app/helpers/api/v1/sessions_helper.rb
module Api::V1::SessionsHelper
end

app/helpers/api/v1/usuarios_helper.rb
module Api::V1::UsuariosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/estaticas_helper.rb
module EstaticasHelper
end

app/helpers/retos_helper.rb
module RetosHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/layouts/_links.html.erb
 <li class="active"><%= link_to 'Inicio',inicio_path%>

                        </li>
                        <%if usuario_signed_in?%>
                        <li><%=link_to 'Editar',edit_usuario_registration_path%>
                        </li>
                        <li><%=link_to 'Mi Perfil',"/usuarios/"+current_usuario.id.to_s %>
                        </li>
                        <li><%=link_to 'Cerrar Sesion',destroy_usuario_session_path(current_usuario),confirm: 'Esta Seguro?', method: :delete%>
                        </li>

                        <%else%>
                        <li><%=link_to 'Iniciar Sesion',new_usuario_session_path %>
                        </li>
                        <li><%=link_to 'Registrarme',new_usuario_registration_path %>
                        </li>
                        <%end%>
                        

                        

app/views/layouts/_navbar.html.erb
<div id="lateral">
            <nav class="navbar navbar-inverse" role="navigation">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand logo" href="index.html">
                        <img class="logo" src="<%= image_url('logo.png') %> " alt="Comunicaciones">
                    </a>
                </div>

                <!-- Elementos de la barra de navegacion -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                       <%=render 'layouts/links'%>
                    </ul>
                </div>
                <!-- /.navbar-collapse -->
            </nav>
        </div>
			
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Comunicaciones</title>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
</head>
<body>
<%= render 'layouts/navbar'%>
<div class="panel">
	<div class="container">
		
		<%= yield %>
		
	</div>
</div>
</body>
</html>